// Automatically generated by astro-icon
// 3845a0934adba2f263c68b13ef4456759b27c6affe89c60e111946f8a0d08583

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "cv-cover-letter"
		| "english-for-it"
		| "general-english"
		| "ielts"
		| "job-interview"
		| "telegram-community";
}