// Automatically generated by astro-icon
// 194ef87fa9a8ed847a4d134a68a79e2ac5bd5c351f6e6b06f85462e6a0131a1c

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "cv-cover-letter"
		| "english-for-it"
		| "general-english"
		| "ielts"
		| "job-interview"
		| "telegram-community"
		| "y_boost_logo";
}